apiVersion: v1
kind: ConfigMap
metadata:
  name: google-config
data:
  google_api.json: |-
    {}

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sentiment_analysis
spec:
  selector:
    matchLabels:
      app: sentiment
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: sentiment
        version: v1
    spec:
      containers:
        - name: sentiment
          image: rayyildiz/sentiment_analyzer
          ports:
            - containerPort: 8080
          env:
            - name: app.http.host
              value: "0.0.0.0"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /apps/conf/google_api.json

          workingDir: /apps
          volumeMounts:
            - mountPath: /apps/conf
              name: config
      volumes:
        - name: config
          configMap:
            name: google-config
            items:
              - key: google_api.json
                path: google_api.json
---
apiVersion: v1
kind: Service
metadata:
  name: sentimentsrv
spec:
  selector:
    app: sentiment
    version: v1
  ports:
    - port: 8080
